window.SMART_DT_ASSETS = {
  illustrations: {
    ideationCard: "https://iili.io/CJ4vBqB.png",
    testCard: "https://iili.io/CJ4vC0P.png",
    prototypeCard: "https://iili.io/CJ4vng1.png",
    defineCard: "https://iili.io/CJ4vz5g.png",
    empathyCard: "https://iili.io/CJ4vcgt.png"
  },
  stats: {
    evidence: "https://iili.io/CJ4ep9a.png",
    badges: "https://iili.io/CJ4k9wv.png",
    tasks: "https://iili.io/CJ4kHtR.png",
    projects: "https://iili.io/CJ4kdnp.png",
    feedback: "https://iili.io/CJ4k3PI.png"
  },
  badges: {
    empathyChampion: "https://iili.io/CJr4kSS.png",
    dtExplorer: "https://iili.io/CJr4SR9.png",
    dtGraduate: "https://iili.io/CJr4UNe.png",
    fullPortfolio: "https://iili.io/CJr4gDu.png",
    ideaGenerator: "https://iili.io/CJr4Pix.png",
    problemFramer: "https://iili.io/CJr6xsf.png",
    prototypeBuilder: "https://iili.io/CJr6557.png",
    milestoneBadge: "https://iili.io/CJr6czu.png",
    userTester: "https://iili.io/CJr6G0Q.png",
    achievementStar: "https://iili.io/CJr6yk7.png",
    dtExplorerBadge: "https://iili.io/CJrPB2V.png"
  },
  ui: {
    globe: "https://iili.io/CJgMoLG.png",
    dashboard: "https://iili.io/CJgMzBf.png",
    chevronDown: "https://iili.io/CJgMI14.png",
    chevronRight: "https://iili.io/CJgMTrl.png",
    learn: "https://iili.io/CJgMA22.png",
    lock: "https://iili.io/CJgMR7S.png",
    menu: "https://iili.io/CJgM5k7.png",
    portfolio: "https://iili.io/CJgMaIe.png",
    print: "https://iili.io/CJgMlLb.png",
    progress: "https://iili.io/CJgM1Bj.png",
    projects: "https://iili.io/CJgMEEx.png",
    quiz: "https://iili.io/CJgMGrQ.png",
    save: "https://iili.io/CJgMV2V.png",
    shield: "https://iili.io/CJgMXkP.png",
    tick: "https://iili.io/CJgMhp1.png",
    upload: "https://iili.io/CJgMwTF.png",
    calendar: "https://iili.io/CJgMNhg.png",
    goal: "https://iili.io/CJg4NBR.png",
    menuAchievement: "https://iili.io/CJrU0c7.png",
    graduation: "https://iili.io/CJrU1S9.png",
    evidenceFiles: "https://iili.io/CJrUG9e.png",
    buildOn: "https://iili.io/CJrUMAu.png",
    menuEdit: "https://iili.io/CJrUhox.png",
    menuLogout: "https://iili.io/CJrUjMQ.png",
    menuPersonal: "https://iili.io/CJrUOKB.png",
    menuReflections: "https://iili.io/CJrUecP.png",
    quickInfo: "https://iili.io/CJrUSAg.png",
    unknown71: "https://iili.io/CJrUUNa.png",
    menuSettings: "https://iili.io/CJrUgDJ.png",
    registrationCard: "https://iili.io/CJrU4ov.png"
  },
  pillar: {
    think: "https://iili.io/CJgxzhX.png",
    improve: "https://iili.io/CJgzrx9.png",
    test: "https://iili.io/CJgz4Ve.png"
  },
  nav: {
    learn: "https://iili.io/CJgFAZv.png",
    dashboard: "https://iili.io/CJgF5nR.png",
    progress: "https://iili.io/CJgF7Gp.png",
    projects: "https://iili.io/CJgFY6N.png",
    portfolio: "https://iili.io/CJgFlat.png"
  },
  shared: { aiCoachIcon: "https://iili.io/CJ4dGtf.png" },
  features: {
    mistake: "https://iili.io/CJUgMfS.png",
    observeUser: "https://iili.io/CJUgWg9.png",
    listen: "https://iili.io/CJUghJe.png",
    interviewUsers: "https://iili.io/CJUgj5u.png",
    observe: "https://iili.io/CJUgwOb.png",
    understand: "https://iili.io/CJUgezx.png",
    empathyOverview: "https://iili.io/CJUgkWQ.png",
    goal: "https://iili.io/CJUgvsV.png",
    understandAlt: "https://iili.io/CJ47Q4I.png",
    startSimple: "https://iili.io/CJ47t2t.png",
    frame: "https://iili.io/CJ47DYX.png",
    refine: "https://iili.io/CJ47bvn.png",
    iterate: "https://iili.io/CJ47mps.png",
    evaluate: "https://iili.io/CJ47yTG.png",
    brainstorm: "https://iili.io/CJ4Y9jf.png",
    analyze: "https://iili.io/CJ4ck42.png"
  },
  dashboard: {
    evidence: "https://iili.io/CJUN95l.png",
    activity: "https://iili.io/CJUNHe2.png",
    feedback: "https://iili.io/CJUN3X9.png",
    team: "https://iili.io/CJUNo5Q.png",
    tasks: "https://iili.io/CJUe65x.png"
  },
  brand: { logo: "https://iili.io/CJUGyZb.png" },
  actions: {
    microphone: "https://iili.io/CJU0Xjf.png",
    print: "https://iili.io/CJU0hQ4.png",
    pause: "https://iili.io/CJU0wCl.png",
    play: "https://iili.io/CJU0NG2.png",
    record: "https://iili.io/CJU08ve.png",
    saveTranscript: "https://iili.io/CJU0Syu.png",
    save: "https://iili.io/CJU0gTb.png",
    stop: "https://iili.io/CJU04Zx.png",
    uploadAudio: "https://iili.io/CJU0PCQ.png",
    audioWave: "https://iili.io/CJU0iGV.png",
    consent: "https://iili.io/CJU0Q3P.png",
    interviewGuide: "https://iili.io/CJ4wp9f.png"
  }
};
